# Data Dictionaries.

bidi = {
    'L': 'LEFT-TO-RIGHT',
    'R': 'RIGHT-TO-LEFT (NON-ARABIC)',
    'AL': 'RIGHT-TO-LEFT (ARABIC)',
    'EN': 'EUROPEAN NUMBER',
    'ES': 'EUROPEAN SEPARATOR',
    'ET': 'EUROPEAN TERMINATOR',
    'AN': 'ARABIC NUMBER',
    'CS': 'COMMON SEPARATOR',
    'NSM': 'NONSPACING MARK',
    'BN': 'BOUNDARY NEUTRAL',
}

category = {
    'Lu': 'UPPERCASE LETTER',
    'Ll': 'LOWERCASE LETTER',
    'Lt': 'TITLECASE LETTER',
    'Lm': 'MODIFIER LETTER',
    'Lo': 'OTHER LETTER',
    'Mn': 'NONSPACING MARK',
    'Mc': 'SPACING MARK',
    'Me': 'ENCLOSING MARK',
    'M': 'MARK',
    'Nd': 'DECIMAL NUMBER',
    'Nl': 'LETTER NUMBER',
    'No': 'OTHER NUMBER',
    'Pc': 'CONNECTOR PUNCTUATION',
    'Pd': 'DASH PUNCTUATION',
    'Ps': 'OPEN PUNCTUATION',
    'Pe': 'CLOSE PUNCTUATION',
    'Pi': 'INITIAL PUNCTUATION',
    'Pf': 'FINAL PUNCTUATION',
    'Po': 'OTHER PUNCTUATION',
    'Sm': 'MATH SYMBOL',
    'Sc': 'CURRENCY SYMBOL',
    'Sk': 'MODIFIER SYMBOL',
    'So': 'OTHER SYMBOL',
    'Zs': 'SPACE SEPARATOR',
    'Zl': 'LINE SEPARATOR',
    'Zp': 'PARAGRAPH SEPARATOR',
    'Cc': 'CONTROL',
    'Cf': 'FORMAT',
    'Cs': 'SURROGATE',
    'Co': 'PRIVATE USE',
    'Cn': 'UNASSIGNED',
}
