# Data Dictionaries.

bidi = {
    'L': 'LEFT-TO-RIGHT',
    'R': 'RIGHT-TO-LEFT (NON-ARABIC)',
    'AL': 'RIGHT-TO-LEFT (ARABIC)',
    'EN': 'EUROPEAN NUMBER',
    'ES': 'EUROPEAN SEPARATOR',
    'ET': 'EUROPEAN TERMINATOR',
    'AN': 'ARABIC NUMBER',
    'CS': 'COMMON SEPARATOR',
    'NSM': 'NONSPACING MARK',
    'BN': 'BOUNDARY NEUTRAL',
}

category = {
    'Lu': 'UPPERCASE LETTER',
    'Ll': 'LOWERCASE LETTER',
    'Lt': 'TITLECASE LETTER',
    'Lm': 'MODIFIER LETTER',
    'Lo': 'OTHER LETTER',
    'Mn': 'NONSPACING MARK',
    'Mc': 'SPACING MARK',
    'Me': 'ENCLOSING MARK',
    'M': 'MARK',
    'Nd': 'DECIMAL NUMBER',
    'Nl': 'LETTER NUMBER',
    'No': 'OTHER NUMBER',
    'Pc': 'CONNECTOR PUNCTUATION',
    'Pd': 'DASH PUNCTUATION',
    'Ps': 'OPEN PUNCTUATION',
    'Pe': 'CLOSE PUNCTUATION',
    'Pi': 'INITIAL PUNCTUATION',
    'Pf': 'FINAL PUNCTUATION',
    'Po': 'OTHER PUNCTUATION',
    'Sm': 'MATH SYMBOL',
    'Sc': 'CURRENCY SYMBOL',
    'Sk': 'MODIFIER SYMBOL',
    'So': 'OTHER SYMBOL',
    'Zs': 'SPACE SEPARATOR',
    'Zl': 'LINE SEPARATOR',
    'Zp': 'PARAGRAPH SEPARATOR',
    'Cc': 'CONTROL',
    'Cf': 'FORMAT',
    'Cs': 'SURROGATE',
    'Co': 'PRIVATE USE',
    'Cn': 'UNASSIGNED',
}

east_asian_categories = {
    'F': 'East Asian Fullwidth',
    'H': 'East Asian Halfwidth',
    'W': 'East Asian Wide',
    'Na': 'East Asian Narrow',
    'A': 'East Asian Ambiguous',
    'N': 'Non East Asian',
}

# Unicode Script property short code -> display name (for homoglyph / lookalike detection).
script_display = {
    'Common': 'Common',
    'Inherited': 'Inherited',
    'Unknown': 'Unknown',
    'Latn': 'Latin',
    'Cyrl': 'Cyrillic',
    'Arab': 'Arabic',
    'Grek': 'Greek',
    'Hebr': 'Hebrew',
    'Hani': 'Han',
    'Hira': 'Hiragana',
    'Kana': 'Katakana',
    'Hang': 'Hangul',
    'Deva': 'Devanagari',
    'Thai': 'Thai',
    'Beng': 'Bengali',
    'Taml': 'Tamil',
    'Telu': 'Telugu',
    'Gujr': 'Gujarati',
    'Knda': 'Kannada',
    'Mlym': 'Malayalam',
    'Mymr': 'Myanmar',
    'Khmr': 'Khmer',
    'Laoo': 'Lao',
    'Tibt': 'Tibetan',
    'Geor': 'Georgian',
    'Armn': 'Armenian',
    'Thaa': 'Thaana',
    'Syrc': 'Syriac',
    'Copt': 'Coptic',
    'Brai': 'Braille',
    'Phag': 'Phags-Pa',
    'Nkoo': 'Nko',
}

# Character name prefix (first word of Unicode name) -> display name when ud.script is unavailable.
name_prefix_to_script = {
    'LATIN': 'Latin',
    'CYRILLIC': 'Cyrillic',
    'ARABIC': 'Arabic',
    'GREEK': 'Greek',
    'HEBREW': 'Hebrew',
    'HAN': 'Han',
    'CJK': 'Han',
    'HIRAGANA': 'Hiragana',
    'KATAKANA': 'Katakana',
    'HANGUL': 'Hangul',
    'DEVANAGARI': 'Devanagari',
    'THAI': 'Thai',
    'BENGALI': 'Bengali',
    'TAMIL': 'Tamil',
    'TELUGU': 'Telugu',
    'GUJARATI': 'Gujarati',
    'KANNADA': 'Kannada',
    'MALAYALAM': 'Malayalam',
    'MYANMAR': 'Myanmar',
    'KHMER': 'Khmer',
    'LAO': 'Lao',
    'TIBETAN': 'Tibetan',
    'GEORGIAN': 'Georgian',
    'ARMENIAN': 'Armenian',
    'THAANA': 'Thaana',
    'SYRIAC': 'Syriac',
    'COPTIC': 'Coptic',
    'BRAILLE': 'Braille',
    'PHAGS-PA': 'Phags-Pa',
    'NKO': 'Nko',
    'COMBINING': 'Inherited',
}